backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://igorfitzone.netlify.app
logo_url: /assets/logo.png

collections:
  - name: "posts"
    label: "Посты и советы"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Фото / видео галерея"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Изображение", name: "image", widget: "image" }

  - name: "reviews"
    label: "Отзывы клиентов"
    folder: "reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя", name: "name", widget: "string" }
      - { label: "Текст отзыва", name: "review", widget: "text" }
      - { label: "Фото клиента", name: "photo", widget: "image" }

  - name: "pricing"
    label: "Прайс и пакеты"
    folder: "pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Цена", name: "price", widget: "number" }

  - name: "partners"
    label: "Партнёрские ссылки"
    folder: "partners"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "name", widget: "string" }
      - { label: "Ссылка", name: "url", widget: "string" }

  - name: "seo"
    label: "SEO и настройки"
    folder: "seo"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Keywords", name: "keywords", widget: "list" }
