backend:
  name: git-gateway
  branch: main
  identity_url: https://igorfitzone.netlify.app/.netlify/identity
  gateway_url: https://igorfitzone.netlify.app/.netlify/git

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Посты и советы"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Фото / видео галерея"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Изображение", name: "image", widget: "image" }

  - name: "reviews"
    label: "Отзывы клиентов"
    folder: "reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя клиента", name: "name", widget: "string" }
      - { label: "Отзыв", name: "text", widget: "text" }

  - name: "pricing"
    label: "Прайс и пакеты"
    folder: "pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Пакет", name: "title", widget: "string" }
      - { label: "Описание", name: "desc", widget: "text" }
      - { label: "Цена", name: "price", widget: "string" }
