backend:
  name: auth0
  domain: igorfitzone.eu.auth0.com
  client_id: HbsyoUaehsFN4KP5nTyGb6JA4Ux0AJlC
  redirect_uri: https://igorfitzone.netlify.app/admin/
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"


collections:
  - name: "posts"
    label: "Посты и советы"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Фото / видео галерея"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Изображение", name: "image", widget: "image" }

  - name: "reviews"
    label: "Отзывы клиентов"
    folder: "reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Имя клиента", name: "name", widget: "string" }
      - { label: "Отзыв", name: "text", widget: "text" }

  - name: "pricing"
    label: "Прайс и пакеты"
    folder: "pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Пакет", name: "title", widget: "string" }
      - { label: "Описание", name: "desc", widget: "text" }
      - { label: "Цена", name: "price", widget: "string" }

