
backend:
  name: git-gateway
  branch: main

locale: ru
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "/"
display_url: "/"

collections:
  - name: "posts"
    label: "📝 Посты и советы"
    folder: "assets/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Изображение (обложка)", name: "cover", widget: "image", required: false}
      - {label: "Содержимое", name: "body", widget: "markdown"}

  - name: "gallery"
    label: "🏋️ Галерея"
    file: "assets/gallery.json"
    fields:
      - label: "Элементы"
        name: "items"
        widget: "list"
        fields:
          - {label: "Изображение", name: "image", widget: "image"}
          - {label: "Тип", name: "type", widget: "select", options: ["image","youtube"], default: "image"}
          - {label: "YouTube ID (если видео)", name: "youtube", widget: "string", required: false}

  - name: "reviews"
    label: "💬 Отзывы"
    file: "assets/reviews.json"
    fields:
      - label: "Отзывы"
        name: "items"
        widget: "list"
        fields:
          - {label: "Имя", name: "name", widget: "string"}
          - {label: "Оценка", name: "stars", widget: "number", min: 1, max: 5, value_type: "int"}
          - {label: "Комментарий", name: "comment", widget: "text"}
          - {label: "Дата", name: "date", widget: "datetime"}

  - name: "pricing"
    label: "💰 Прайс и пакеты"
    file: "assets/pricing.json"
    fields:
      - label: "Пакеты"
        name: "plans"
        widget: "list"
        fields:
          - {label: "Название", name: "name", widget: "string"}
          - {label: "Цена (PLN)", name: "price", widget: "number"}
          - {label: "Описание", name: "desc", widget: "text"}
          - {label: "PayPal Label", name: "paypal_label", widget: "string", default: "Оплатить"}

  - name: "partners"
    label: "🔗 Партнёрские блоки"
    file: "assets/partners.json"
    fields:
      - label: "Рекомендации"
        name: "partners"
        widget: "list"
        fields:
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Ссылка", name: "url", widget: "string"}
          - {label: "Баннер", name: "image", widget: "image"}

  - name: "settings"
    label: "⚙️ SEO и настройки"
    file: "assets/settings.json"
    fields:
      - {label: "Google Analytics ID", name: "ga_id", widget: "string", default: "G-KJNZSMGH2D"}
      - {label: "PayPal Client ID", name: "paypal_client_id", widget: "string", default: "Af7s4XmMDf4ZgqXdRtJRvTFEmZNLAn6cafmbz6wYHjLDh8eoo2IuvkwA_uMtC_j7DsIFsn99mJKDcJUI"}
      - {label: "Make Webhook URL", name: "make_webhook", widget: "string", default: "https://hook.eu2.make.com/ia83okvtkus5ddgpuay3t772lvrn2dyk"}
      - {label: "Ключевые слова (SEO)", name: "keywords", widget: "text", default: "фитнес тренер Варшава, персональные тренировки, нутрициолог, снижение веса, набор массы, тренировки для мужчин, CityFit Warsaw"}
      - {label: "OG‑изображение", name: "og_image", widget: "image", required: false}
